[package]
name = "merkle_tree"
version = "0.1.0"
edition = "2021"

[dependencies]
blake2 = "0.10.5"
displaydoc = "0.2.3"
lazy_static = "1.4.0"
sha3 = "0.10.6"

[dev-dependencies]
hex = "0.4.3"
hex-literal = "0.3.4"
